# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 04:38
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivePage',
            fields=[
                ('oldmgid', models.TextField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('download_link', models.TextField(blank=True, null=True)),
                ('direct_link', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('tsv', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'archive',
            },
        ),
        migrations.RunSQL(("CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE "
                            "ON archive FOR EACH ROW EXECUTE PROCEDURE "
                            "tsvector_update_trigger(tsv, 'pg_catalog.english', text);")),
        migrations.RunSQL("CREATE INDEX text_index ON archive USING GIN (tsv);")
    ]
